# PyTorch exercises (https://www.learnpytorch.io/)

## 00 PyTorch fundementals

In [21]:
import torch as t

t.manual_seed(0)
tensor1 = t.rand(7,7)
tensor2 = t.rand(1,7)
print(tensor1)
print(tensor2.T)

print(tensor1.matmul(tensor2.T))

t.cuda.manual_seed(0)
#exercises 2-5

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [22]:
t.manual_seed(1234)
tensor3 = t.rand(2,3)
tensor4 = t.rand(2,3)

matmulTensor = t.matmul(tensor3, tensor4.T)
print(matmulTensor.min())
print(matmulTensor.max())
print(matmulTensor.size())
#exercises 6-9

tensor(0.3647)
tensor(0.5617)
torch.Size([2, 2])


In [23]:
t.manual_seed(7)
tensor5 = t.rand(1,1,1,10)
tensorSqueezed= tensor5.squeeze()
print(tensor5, tensor5.size())
print(tensorSqueezed, tensorSqueezed.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
