# PyTorch basics and fundamentals

## Tensors and Tensor operations


### Tensor basics: Initialization and Modification

In [1]:
import torch as t
from torch import tensor

torchTensor = tensor([[1, 2, 3],
                      [4, 5, 6]])
#y = tensor([[1, 2, 3],
#            [4, 5]])
print("ndims: " + str(torchTensor.ndim) + "  " + str(torchTensor.shape))

ndims: 2  torch.Size([2, 3])


A ***tensor*** is akin to an n-dimensional array of one specific datatype. Every dimension always has to be the same length, so tensor y would produce a ***ValueError*** because of invalid sizes. The tensors variable **ndim** is equal to its number of total dimensions and its variable **shape** displays its length in every one of its dimensions.

In [2]:
print(torchTensor)
print(torchTensor.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


The constant **tensor.T** is a _transposed_ (mirrored and flipped) version of the tensor.

In [3]:
print(torchTensor.zero_())


tensor([[0, 0, 0],
        [0, 0, 0]])


In [4]:
tensor_a = t.arange(0, 48, 4)
print(tensor_a)

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])


Using **torch.arange(start, end, step),** you can create a one dimensional tensor with values from start to end that increase by step.

### Tensor operations

In [5]:
import torch as t
torchTensor = tensor([[1, 2, 3],
                      [4, 5, 6]])
print(torchTensor)
print(torchTensor.T, end="\n\n")
print(torchTensor * torchTensor)
print(torchTensor.matmul(torchTensor.T))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[14, 32],
        [32, 77]])


Tensors can be **multiplied** like regular matrices, which is done by multiplying each element with the element in the same place on the other tensor.
 ***
 _Matrix multiplication_ is a special kind of multiplication that is only possible when the **inner dimensions** match (e.g. t.size(3, 2) and t.size(2, 3)). This is done by multiplying the ***dotproducts*** of the rows and columns of the tensors/matricies.

See more about matrix multiplication at: https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [6]:
tensor_a = t.arange(0, 48, 4).reshape(3, 4)
print(tensor_a)
print(tensor_a.min())
print(tensor_a.max())
#print(tensor.mean()) "TypeError: "Input dtype must be either a floating point or complex dtype. Got: Long"
print(tensor_a.mean(dtype=t.float32))
print(tensor_a.sum())
print(tensor_a.type(t.complex128)) #complex dtypes range from 32 (cHalf) to 128

tensor([[ 0,  4,  8, 12],
        [16, 20, 24, 28],
        [32, 36, 40, 44]])
tensor(0)
tensor(44)
tensor(22.)
tensor(264)
tensor([[ 0.+0.j,  4.+0.j,  8.+0.j, 12.+0.j],
        [16.+0.j, 20.+0.j, 24.+0.j, 28.+0.j],
        [32.+0.j, 36.+0.j, 40.+0.j, 44.+0.j]], dtype=torch.complex128)


With methods such as **min, max, mean** or **sum,** you can calculate values from the tensor. ***Be careful!*** Some methods require floating-point or complex datatypes instead of ints. This can be achieved by either specifying the type within the method or using the method .type(dtype) beforehand. For PyTorch functions and methods, **only PyTorch datatypes** can be used.

In [7]:
print(tensor_a.argmin())
print(tensor_a.argmax())

tensor(0)
tensor(11)


The **.argmin()** and **.argmax()** methods are closely related to its min and max counterparts. Instead of the min and max value of the tensor, they both show the positions of those values **within the tensor**.
- all the calculation methods shown above can be used as static functions from the class torch as well.
- all the calculation methods shown above are called tensor aggregation

In [8]:
print(tensor_a[2][3])
print(torchTensor[0])

tensor(44)
tensor([1, 2, 3])


Tensor elements can be accessed just like regular list or array elements. This is called **indexing** a tensor.

### Reshaping, viewing and squeezing a tensor

In [9]:
import torch as t
torchTensor = t.arange(1., 13.)

print(torchTensor)
print(torchTensor.reshape(3, 4))


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


With the function **.reshape(dimension1, dimension2, dimensionN...),** an already existing tensor can be reshaped into the dimensions given. The product of all dimensions **has to be equal** to the number of elements in the tensor for it to fit the new shape.

In [10]:
z = torchTensor.view(1, 12)
print(z)

#changing the first element of z
z[0, 0] = 500.
print(z)
print(torchTensor)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])
tensor([500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.])


View is quite similar to reshape in the sense that they **both change the dimensions of a tensor.** The difference is, that reshape returns a new object, while view **shares the memory with the original element.** Therefore, even though z might look different, they both access the same element in memory so **changing one will also change the other.**

In [11]:
x_stacked = t.stack([torchTensor, torchTensor])
print(x_stacked)
x_stacked = t.stack([torchTensor, torchTensor], dim=1)
print(x_stacked)
x_stacked = t.stack([torchTensor, torchTensor], dim=0)
print(x_stacked)

tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.],
        [500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])
tensor([[500., 500.],
        [  2.,   2.],
        [  3.,   3.],
        [  4.,   4.],
        [  5.,   5.],
        [  6.,   6.],
        [  7.,   7.],
        [  8.,   8.],
        [  9.,   9.],
        [ 10.,  10.],
        [ 11.,  11.],
        [ 12.,  12.]])
tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.],
        [500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])


Stacking tensors with the **.stack(tensors[])** function will combine them to a single tensor by **concatenating/adding them on the dimension given.** Changing the parameter **dim** to another dimension will stack them in a different way. For example, with dim=1 like in the example, the tensor will become of size(12, 2), where each of the pairs of numbers consists of the numbers that were in that index **before the stack.** The default value for dim is 0.
- note: this function requires the sizes of the tensors to be equal

In [12]:
tensor_b = t.arange(1, 11).reshape(1, 5, 1, 2)
print(f"Previous tensor: {tensor_b}")
print(f"Previous tensor shape: {tensor_b.shape}")
squeezed_tensor = tensor_b.squeeze()
print(f"New tensor: {squeezed_tensor}")
print(f"New tensor shape: {squeezed_tensor.shape}", end="\n\n")

unsqueezed_tensor = tensor_b.unsqueeze(dim=4)
print(f"New tensor: {unsqueezed_tensor}")
print(f"New tensor shape: {unsqueezed_tensor.shape}")


Previous tensor: tensor([[[[ 1,  2]],

         [[ 3,  4]],

         [[ 5,  6]],

         [[ 7,  8]],

         [[ 9, 10]]]])
Previous tensor shape: torch.Size([1, 5, 1, 2])
New tensor: tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
New tensor shape: torch.Size([5, 2])

New tensor: tensor([[[[[ 1],
           [ 2]]],


         [[[ 3],
           [ 4]]],


         [[[ 5],
           [ 6]]],


         [[[ 7],
           [ 8]]],


         [[[ 9],
           [10]]]]])
New tensor shape: torch.Size([1, 5, 1, 2, 1])


As seen in the example, tensor_b has a lot of "unnecessary" dimensions of size 1. The **.squeeze()** method simply deletes those dimensions. If you look at the size parameter, you will quickly notice all the ones being gone.
***
The **unsqueeze(dim)** method reverses this process by adding an extra dimension at the dimension given. The default value is 0 and the dimensions start from the outside in.

In [13]:
tensor_c = t.randn(5, 2, 3)
print(f"tensor : {tensor_c}")
print(f"tensor shape : {tensor_c.shape}", end="\n\n")
permuted = tensor_c.permute(2, 0, 1)
print(f"new permuted tensor: {permuted}")
print(f"new permuted tensor shape: {permuted.shape}", end="\n\n")

#permuted = permuted.permute(3, 1, 0)       #IndexError: Dimension out of range
#permuted = permuted.permute(1, 0)          #RuntimeError: number of dimensions in the tensor input does not match the length of the desired ordering of dimensions
#print(f"new permuted tensor: {permuted}")
#print(f"new permuted tensor shape: {permuted.shape}", end="\n\n")

tensor : tensor([[[ 0.0249,  0.9914,  0.8370],
         [-0.6334,  1.5780, -1.2530]],

        [[-0.2178,  0.6787, -0.5003],
         [ 1.2004,  0.1234,  2.1369]],

        [[ 1.5867,  0.4365,  0.0639],
         [ 1.0323, -0.3904,  0.7606]],

        [[-0.8645,  1.1869,  0.6207],
         [-0.5401,  0.7743,  0.5703]],

        [[ 0.4065, -0.8439, -0.1915],
         [ 1.6352,  0.8942, -0.0034]]])
tensor shape : torch.Size([5, 2, 3])

new permuted tensor: tensor([[[ 0.0249, -0.6334],
         [-0.2178,  1.2004],
         [ 1.5867,  1.0323],
         [-0.8645, -0.5401],
         [ 0.4065,  1.6352]],

        [[ 0.9914,  1.5780],
         [ 0.6787,  0.1234],
         [ 0.4365, -0.3904],
         [ 1.1869,  0.7743],
         [-0.8439,  0.8942]],

        [[ 0.8370, -1.2530],
         [-0.5003,  2.1369],
         [ 0.0639,  0.7606],
         [ 0.6207,  0.5703],
         [-0.1915, -0.0034]]])
new permuted tensor shape: torch.Size([3, 5, 2])



A ***Permutation*** of a tensor is similar to a *view*, as it shares the same memory as the original tensor. However, instead of choosing new sizes for the dimensions, the original dimensions are swapped around. This can be done with the **torch.permute()** function.

**Be Careful!** The passed arguments of the permute function may not exceed the index of the length of the .size() array-like attribute of the tensor and the number of arguments has to match the size the tensors size.

In [19]:
image_tensor = t.randn(size=(64, 64, 3))    #[height, width, color channels]
print(f"Unpermuted tensor (wrong format): {image_tensor.shape}")
#reshapint => permuting:
permuted_image_tensor = image_tensor.permute(2, 0, 1)   #[color channels, height, width]
print(f"permuted tensor shape: {permuted_image_tensor.shape}", end="\n\n")


Unpermuted tensor (wrong format): tensor([[[-0.4074, -0.1718, -0.7832],
         [ 0.3661, -0.0280,  0.1675],
         [-1.4622,  0.4904,  0.8869],
         ...,
         [-0.6594, -0.5430,  0.0691],
         [-1.4136,  1.1507, -0.3544],
         [-1.5259, -0.0785, -0.2005]],

        [[-0.8488,  0.5452, -0.1768],
         [ 0.5927,  0.5107, -0.7922],
         [-1.8830, -0.4976, -0.1808],
         ...,
         [-0.5618,  0.5860,  1.5210],
         [-1.6848, -1.0047,  0.0801],
         [-1.7217,  0.7508, -0.1226]],

        [[-0.0718, -0.5788, -0.2363],
         [ 0.1983, -1.5316, -1.0017],
         [-1.2460,  1.4388, -1.4014],
         ...,
         [-0.8141, -2.0274, -0.7892],
         [-0.9721, -0.2935, -0.8404],
         [-0.2425, -0.2229,  0.1670]],

        ...,

        [[-0.2223,  1.2604,  0.5197],
         [ 1.5688, -0.8050, -1.4183],
         [ 0.6307, -1.9751, -1.2202],
         ...,
         [ 0.8139,  0.6711,  0.1058],
         [ 0.6434,  0.6074, -0.6081],
         [-1.356

A common use of Permutations is in turning images into the correct data format of tensors.

### Indexing/selecting data from tensors

In [20]:
import torch as t
torchTensor = t.arange(0, 10).reshape(1, 2, 5)
torchTensor, torchTensor.shape

(tensor([[[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]]]),
 torch.Size([1, 2, 5]))

Indexing on **pyTorch tensors** is the same as indexing on numPy arrays, which is the same as Java arrays.

In [7]:
print(torchTensor[0])         #indexing on the first dimension
print(torchTensor[0, 0])      #indexing on the second dimension
print(torchTensor[0, 0, 0])   #indexing on the third dimension

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor(0)


In [8]:
print(torchTensor[0])
print(torchTensor[0][0])
print(torchTensor[0][0][0])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor(0)


Indexing works either the same as in Java, where you separate the dimensions with square brackets, or like in numPy, where you separate the dimensions with commas.
***
You can also use *":"* to select **all** of a dimension. In this example: get all elements of the 0th and 1st dimension, but only the second ones from the 2nd dimension

In [21]:
print(torchTensor)
print(torchTensor[0, :, 1])  #0th, 1st, 2nd dimension
#selecting all from the 1st that are on index 1 in the 2nd

tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])
tensor([1, 6])


One more example: get all values from the 1st dimension that have index 1 in the 2nd dimension

In [10]:
print(torchTensor[:, 0, 0])
print(torchTensor[0, 0, 0])

tensor([0])
tensor(0)


***Note:*** Indexing with a ":" returns a pyTorch array compared to a tensor value, because it could be multiple elements.

### PyTorch tensors & NumPy

**NumPy** is a popular Python *numerical computing library*. PyTorch actually requires NumPy to function and NumPy comes installed with it. That's why PyTorch tensors have a lot of similarities and are really compatible with NumPy ndArrays.

In [37]:
import torch as t
import numpy as np

torchTensor = t.arange(0., 30., 5).reshape(1, 2, 3)
fromPyTorch = t.Tensor.numpy(torchTensor)
print(f"Converted to Pytorch to Numpy: {fromPyTorch}, datatype: {fromPyTorch.dtype}")
ndArray = np.arange(0., 30., 5).reshape(1, 2, 3)
fromNumPy = t.from_numpy(ndArray)
print(f"Converted from Numpy to Pytorch: {fromNumPy}, datatype: {fromNumPy.dtype}")

Converted to Pytorch to Numpy: [[[ 0.  5. 10.]
  [15. 20. 25.]]], datatype: float32
Converted from Numpy to Pytorch: tensor([[[ 0.,  5., 10.],
         [15., 20., 25.]]], dtype=torch.float64), datatype: torch.float64


***Note:*** Be careful when converting float ndArrays to float Tensors, as tensors use float32 by default, while ndArrays use float64. This problem only occurs during the conversion from NumPy to Torch though.

In [38]:
tTensor = t.arange(1., 6.)
ndArray = np.arange(1., 6.)
print(f"default types: {tTensor.dtype} (PyTorch), {ndArray.dtype} (NumPy)", end="\n\n")
toNp = t.Tensor.numpy(tTensor)
toTorch = t.from_numpy(ndArray)
print(f"converted types: {toNp.dtype} (to NumPy), {toTorch.dtype} (to PyTorch)")

default types: torch.float32 (PyTorch), float64 (NumPy)

converted types: float32 (to NumPy), torch.float64 (to PyTorch)


In [39]:
torchTensor = t.ones(5)
ndArray = t.Tensor.numpy(torchTensor)
#x += ndArray[0]
#x += ndArray[0]
torchTensor += 1
ndArray += 1
#x[0] = 10

#Note: the 2 arrays are kind of connected when I use +=, I have no clue what's happening
torchTensor, ndArray

(tensor([3., 3., 3., 3., 3.]), array([3., 3., 3., 3., 3.], dtype=float32))

In [40]:
torchTensor = torchTensor + 1
ndArray[0] = 10

torchTensor, ndArray

(tensor([4., 4., 4., 4., 4.]), array([10.,  3.,  3.,  3.,  3.], dtype=float32))

When converting a tensor/ndArray, the resulting array should **not** share the same memory as the old one, so they are independent of one another.
***
**In my example**, a new cell for whatever reason achieves this effect.

In [58]:
newNumPy = np.arange(0, 11)
pyTorchConversion = t.from_numpy(newNumPy).type(t.float32)
backToNumpy = t.Tensor.numpy(pyTorchConversion).astype(np.float64)

newNumPy += 1
pyTorchConversion -= 1

newNumPy, pyTorchConversion, backToNumpy
#WHAT IS HAPPENING

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

This problem occurs in ***both*** directions, unless I change the datatype back into the standard for that library again.

## Preparation for a first neural network

### Reproducibility - taking the random out of random


In short, a **neural network** functions by generating *random numbers* and updating those through *tensor operations* to make them a better representation of what they should be. These updates can always be made the same, because you can just reuse the same learning set. The starting numbers however are generated ***pseudorandomly*** and can be controlled with setting a **random seed**.

In [146]:
import torch as t

random_A = t.rand(3, 3)
random_B = t.rand(3, 3)
#random every time

random_A, random_B

(tensor([[0.8816, 0.9391, 0.0892],
         [0.0294, 0.8905, 0.4390],
         [0.2893, 0.4123, 0.0833]]),
 tensor([[0.5740, 0.3409, 0.8669],
         [0.8151, 0.3721, 0.2076],
         [0.2778, 0.5773, 0.1589]]))

In [151]:
#Setting a seed before creating new tensors
RANDOM_SEED = 37
t.manual_seed(RANDOM_SEED)
random_C = t.rand(3, 3)
random_D = t.rand(3, 3)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.7911, 0.6419, 0.8091],
        [0.1659, 0.3555, 0.6189],
        [0.9651, 0.2761, 0.7416]])
tensor([[0.6938, 0.1613, 0.1365],
        [0.4800, 0.9127, 0.8418],
        [0.2175, 0.1866, 0.0027]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


manual_see() ensures, that the "random" data generated is always the same, but the tensors are still different. This is because all the random numbers generated "advance the random queue". To fix this, you have to set the seed a second time before generating new random numbers of any form.

In [155]:
#Setting a seed before creating new tensors
RANDOM_SEED = 37
t.manual_seed(RANDOM_SEED)
random_C = t.rand(3, 3)
t.manual_seed(RANDOM_SEED) #setting the seed a second time before creating a second tensor
random_D = t.rand(3, 3)

print(random_C)
print(random_D)
print(random_C == random_D)
#All true :)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


Extra reproducibility resources:
- https://docs.pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

### Running PyTorch on a GPU

PyTorch gives you the ability to choose which device you want to compute your calculations on. Thanks to NVIDIA hardware and CUDA, these computations can also be assigned to a GPU, which allows for significantly faster runtimes. Using your own GPU takes a little setup beforehand, as you need CUDA and necessary GPU drivers. CUDA can be installed with the command below:

pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130

In [11]:
import torch as t

print(t.cuda.is_available())
print(t.version.cuda)
print(t.cuda.device_count())
print(t.cuda.get_device_name(0))

True
13.0
1
NVIDIA GeForce RTX 4060 Laptop GPU
0


To actually **use** your GPU, you have to manually tell pyTorch though. This can be done on a single **tensor** but *also* a whole ***model***.

In [14]:
device = t.device("cuda" if t.cuda.is_available() else "cpu")

fastTensor = t.arange(1., 31.).reshape(2, 3, 5)
print(fastTensor)
print(fastTensor.device)
fastTensor = fastTensor.to(device)
print(fastTensor.device)

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]],

        [[16., 17., 18., 19., 20.],
         [21., 22., 23., 24., 25.],
         [26., 27., 28., 29., 30.]]])
cpu
cuda:0


Since pyTorch can use both the GPU and the CPU, it's the **best practice** to check if cuda is available *first* and use the cpu instead if not.

In [20]:
#fastNumpyTensor = fastTensor.numpy()     #generates a TypeError
#print(fastNumpyTensor)

There are certain conditions in which you want to move a tensor back onto the GPU. For example, when converting a torch tensor to numPy, the device **has** to be the CPU, or else it will throw a typeError like in the example above.

In [19]:
tensorOnCPU = fastTensor.cpu().numpy()
print(tensorOnCPU, tensorOnCPU.device)
#converted to a ndArray

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]] cpu
