# PyTorch basics and fundamentals

## Chapter one: Tensors and Tensor operations


### Tensor basics: Initialization and Modification

In [1]:
import torch as t
from torch import tensor

x = tensor([[1, 2, 3],
              [4, 5, 6]])
#y = tensor([[1, 2, 3],
#            [4, 5]])
print("ndims: " + str(x.ndim) + "  " + str(x.shape))

ndims: 2  torch.Size([2, 3])


A ***tensor*** is akin to an n-dimensional array of one specific datatype. Every dimension always has to be the same length, so tensor y would produce a ***ValueError*** because of invalid sizes. The tensors variable **ndim** is equal to its number of total dimensions and its variable **shape** displays its length in every one of its dimensions.

In [2]:
print(x)
print(x.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


The constant **tensor.T** is a _transposed_ (mirrored and flipped) version of the tensor.

In [3]:
print(x.zero_())


tensor([[0, 0, 0],
        [0, 0, 0]])


In [4]:
tensor_a = t.arange(0, 48, 4)
print(tensor_a)

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])


Using **torch.arange(start, end, step),** you can create a one dimensional tensor with values from start to end that increase by step.

### Tensor operations

In [5]:
import torch as t
x = tensor([[1, 2, 3],
              [4, 5, 6]])
print(x)
print(x.T, end="\n\n")
print(x*x)
print(x.matmul(x.T))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[14, 32],
        [32, 77]])


Tensors can be **multiplied** like regular matrices, which is done by multiplying each element with the element in the same place on the other tensor.
 ***
 _Matrix multiplication_ is a special kind of multiplication that is only possible when the **inner dimensions** match (e.g. t.size(3, 2) and t.size(2, 3)).


In [6]:
tensor_a = t.arange(0, 48, 4).reshape(3, 4)
print(tensor_a)
print(tensor_a.min())
print(tensor_a.max())
#print(tensor.mean()) "TypeError: "Input dtype must be either a floating point or complex dtype. Got: Long"
print(tensor_a.mean(dtype=t.float32))
print(tensor_a.sum())
print(tensor_a.type(t.complex128)) #complex dtypes range from 32 (cHalf) to 128

tensor([[ 0,  4,  8, 12],
        [16, 20, 24, 28],
        [32, 36, 40, 44]])
tensor(0)
tensor(44)
tensor(22.)
tensor(264)
tensor([[ 0.+0.j,  4.+0.j,  8.+0.j, 12.+0.j],
        [16.+0.j, 20.+0.j, 24.+0.j, 28.+0.j],
        [32.+0.j, 36.+0.j, 40.+0.j, 44.+0.j]], dtype=torch.complex128)


With methods such as **min, max, mean** or **sum,** you can calculate values from the tensor. ***Be careful!*** Some methods require floating-point or complex datatypes instead of ints. This can be achieved by either specifying the type within the method or using the method .type(dtype) beforehand. For PyTorch functions and methods, **only PyTorch datatypes** can be used.

In [7]:
print(tensor_a.argmin())
print(tensor_a.argmax())

tensor(0)
tensor(11)


The **.argmin()** and **.argmax()** methods are closely related to its min and max counterparts. Instead of the min and max value of the tensor, they both show the positions of those values **within the tensor**.
- all the calculation methods shown above can be used as static functions from the class torch as well.
- all the calculation methods shown above are called tensor aggregation

In [8]:
print(tensor_a[2][3])
print(x[0])

tensor(44)
tensor([1, 2, 3])


Tensor elements can be accessed just like regular list or array elements. This is called **indexing** a tensor.

### Reshaping, viewing and squeezing a tensor

In [9]:
import torch as t
x = t.arange(1., 13.)

print(x)
print(x.reshape(3, 4))


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


With the function **.reshape(dimension1, dimension2, dimensionN...),** an already existing tensor can be reshaped into the dimensions given. The product of all dimensions **has to be equal** to the number of elements in the tensor for it to fit the new shape.

In [10]:
z = x.view(1, 12)
print(z)

#changing the first element of z
z[0, 0] = 500.
print(z)
print(x)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])
tensor([500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.])


View is quite similar to reshape in the sense that they **both change the dimensions of a tensor.** The difference is, that reshape returns a new object, while view **shares the memory with the original element.** Therefore, even though z might look different, they both access the same element in memory so **changing one will also change the other.**

In [11]:
x_stacked = t.stack([x, x])
print(x_stacked)
x_stacked = t.stack([x, x], dim=1)
print(x_stacked)
x_stacked = t.stack([x, x], dim=0)
print(x_stacked)

tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.],
        [500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])
tensor([[500., 500.],
        [  2.,   2.],
        [  3.,   3.],
        [  4.,   4.],
        [  5.,   5.],
        [  6.,   6.],
        [  7.,   7.],
        [  8.,   8.],
        [  9.,   9.],
        [ 10.,  10.],
        [ 11.,  11.],
        [ 12.,  12.]])
tensor([[500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.],
        [500.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])


Stacking tensors with the **.stack(tensors[])** function will combine them to a single tensor by **concatenating/adding them on the dimension given.** Changing the parameter **dim** to another dimension will stack them in a different way. For example, with dim=1 like in the example, the tensor will become of size(12, 2), where each of the pairs of numbers consists of the numbers that were in that index **before the stack.** The default value for dim is 0.
- note: this function requires the sizes of the tensors to be equal

In [12]:
tensor_b = t.arange(1, 11).reshape(1, 5, 1, 2)
print(f"Previous tensor: {tensor_b}")
print(f"Previous tensor shape: {tensor_b.shape}")
squeezed_tensor = tensor_b.squeeze()
print(f"New tensor: {squeezed_tensor}")
print(f"New tensor shape: {squeezed_tensor.shape}", end="\n\n")

unsqueezed_tensor = tensor_b.unsqueeze(dim=4)
print(f"New tensor: {unsqueezed_tensor}")
print(f"New tensor shape: {unsqueezed_tensor.shape}")


Previous tensor: tensor([[[[ 1,  2]],

         [[ 3,  4]],

         [[ 5,  6]],

         [[ 7,  8]],

         [[ 9, 10]]]])
Previous tensor shape: torch.Size([1, 5, 1, 2])
New tensor: tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
New tensor shape: torch.Size([5, 2])

New tensor: tensor([[[[[ 1],
           [ 2]]],


         [[[ 3],
           [ 4]]],


         [[[ 5],
           [ 6]]],


         [[[ 7],
           [ 8]]],


         [[[ 9],
           [10]]]]])
New tensor shape: torch.Size([1, 5, 1, 2, 1])


As seen in the example, tensor_b has a lot of "unnecessary" dimensions of size 1. The **.squeeze()** method simply deletes those dimensions. If you look at the size parameter, you will quickly notice all the ones being gone.
***
The **unsqueeze(dim)** method reverses this process by adding an extra dimension at the dimension given. The default value is 0 and the dimensions start from the outside in.

In [13]:
tensor_c = t.randn(5, 2, 3)
print(f"tensor : {tensor_c}")
print(f"tensor shape : {tensor_c.shape}", end="\n\n")
permuted = tensor_c.permute(2, 0, 1)
print(f"new permuted tensor: {permuted}")
print(f"new permuted tensor shape: {permuted.shape}", end="\n\n")

#permuted = permuted.permute(3, 1, 0)       #IndexError: Dimension out of range
#permuted = permuted.permute(1, 0)          #RuntimeError: number of dimensions in the tensor input does not match the length of the desired ordering of dimensions
#print(f"new permuted tensor: {permuted}")
#print(f"new permuted tensor shape: {permuted.shape}", end="\n\n")

tensor : tensor([[[ 0.0249,  0.9914,  0.8370],
         [-0.6334,  1.5780, -1.2530]],

        [[-0.2178,  0.6787, -0.5003],
         [ 1.2004,  0.1234,  2.1369]],

        [[ 1.5867,  0.4365,  0.0639],
         [ 1.0323, -0.3904,  0.7606]],

        [[-0.8645,  1.1869,  0.6207],
         [-0.5401,  0.7743,  0.5703]],

        [[ 0.4065, -0.8439, -0.1915],
         [ 1.6352,  0.8942, -0.0034]]])
tensor shape : torch.Size([5, 2, 3])

new permuted tensor: tensor([[[ 0.0249, -0.6334],
         [-0.2178,  1.2004],
         [ 1.5867,  1.0323],
         [-0.8645, -0.5401],
         [ 0.4065,  1.6352]],

        [[ 0.9914,  1.5780],
         [ 0.6787,  0.1234],
         [ 0.4365, -0.3904],
         [ 1.1869,  0.7743],
         [-0.8439,  0.8942]],

        [[ 0.8370, -1.2530],
         [-0.5003,  2.1369],
         [ 0.0639,  0.7606],
         [ 0.6207,  0.5703],
         [-0.1915, -0.0034]]])
new permuted tensor shape: torch.Size([3, 5, 2])



A ***Permutation*** of a tensor is similar to a *view*, as it shares the same memory as the original tensor. However, instead of choosing new sizes for the dimensions, the original dimensions are swapped around. This can be done with the **torch.permute()** function.

**Be Careful!** The passed arguments of the permute function may not exceed the index of the length of the .size() array-like attribute of the tensor and the number of arguments has to match the size the tensors size.

In [19]:
image_tensor = t.randn(size=(64, 64, 3))    #[height, width, color channels]
print(f"Unpermuted tensor (wrong format): {image_tensor.shape}")
#reshapint => permuting:
permuted_image_tensor = image_tensor.permute(2, 0, 1)   #[color channels, height, width]
print(f"permuted tensor shape: {permuted_image_tensor.shape}", end="\n\n")

Unpermuted tensor (wrong format): tensor([[[-0.4074, -0.1718, -0.7832],
         [ 0.3661, -0.0280,  0.1675],
         [-1.4622,  0.4904,  0.8869],
         ...,
         [-0.6594, -0.5430,  0.0691],
         [-1.4136,  1.1507, -0.3544],
         [-1.5259, -0.0785, -0.2005]],

        [[-0.8488,  0.5452, -0.1768],
         [ 0.5927,  0.5107, -0.7922],
         [-1.8830, -0.4976, -0.1808],
         ...,
         [-0.5618,  0.5860,  1.5210],
         [-1.6848, -1.0047,  0.0801],
         [-1.7217,  0.7508, -0.1226]],

        [[-0.0718, -0.5788, -0.2363],
         [ 0.1983, -1.5316, -1.0017],
         [-1.2460,  1.4388, -1.4014],
         ...,
         [-0.8141, -2.0274, -0.7892],
         [-0.9721, -0.2935, -0.8404],
         [-0.2425, -0.2229,  0.1670]],

        ...,

        [[-0.2223,  1.2604,  0.5197],
         [ 1.5688, -0.8050, -1.4183],
         [ 0.6307, -1.9751, -1.2202],
         ...,
         [ 0.8139,  0.6711,  0.1058],
         [ 0.6434,  0.6074, -0.6081],
         [-1.356

A common use of Permutations is in turning images into the correct data format of tensors.

### Indexing/selecting data from tensors

In [20]:
import torch as t
x = t.arange(0, 10).reshape(1, 2, 5)
x, x.shape

(tensor([[[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]]]),
 torch.Size([1, 2, 5]))

Indexing on **pyTorch tensors** is the same as indexing on numPy arrays, which is the same as Java arrays.

In [21]:
print(x[0])         #indexing on the first dimension
print(x[0, 0])      #indexing on the second dimension
print(x[0, 0, 0])   #indexing on the third dimension

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor(0)


In [23]:
print(x[0])
print(x[0][0])
print(x[0][0][0])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([0, 1, 2, 3, 4])
tensor(0)


Indexing works either the same as in Java, where you separate the dimensions with square brackets, or like in numPy, where you separate the dimensions with commas.
***
You can also use *":"* to select **all** of a dimension. In this example: get all elements of the 0th and 1st dimension, but only the second ones from the 2nd dimension

In [25]:
print(x[:, :, 1])

tensor([[1, 6]])


One more example: get all values of the 0th dimension but only the 1st index of the 1st and 2nd dimension

In [30]:
print(x[:, 0, 0])
print(x[0, 0, 0])

tensor([0])
tensor(0)


***Note:*** Indexing with a ":" returns a pyTorch array compared to a tensor value, because it could be multiple elements.

### PyTorch tensors & NumPy

**NumPy** is a popular Python *numerical computing library*. PyTorch actually requires NumPy to function and NumPy comes installed with it. That's why PyTorch tensors have a lot of similarities and are really compatible with NumPy ndArrays.

In [37]:
import torch as t
import numpy as np

x = t.arange(0., 30., 5).reshape(1, 2, 3)
fromPyTorch = t.Tensor.numpy(x)
print(f"Converted to Pytorch to Numpy: {fromPyTorch}, datatype: {fromPyTorch.dtype}")
ndArray = np.arange(0., 30., 5).reshape(1, 2, 3)
fromNumPy = t.from_numpy(ndArray)
print(f"Converted from Numpy to Pytorch: {fromNumPy}, datatype: {fromNumPy.dtype}")

Converted to Pytorch to Numpy: [[[ 0.  5. 10.]
  [15. 20. 25.]]], datatype: float32
Converted from Numpy to Pytorch: tensor([[[ 0.,  5., 10.],
         [15., 20., 25.]]], dtype=torch.float64), datatype: torch.float64


***Note:*** Be careful when converting float ndArrays to float Tensors, as tensors use float32 by default, while ndArrays use float64. This problem only occurs during the conversion from NumPy to Torch though.

In [41]:
tTensor = t.arange(1., 6.)
ndArray = np.arange(1., 6.)
print(f"default types: {tTensor.dtype} (PyTorch), {ndArray.dtype} (NumPy)", end="\n\n")
toNp = t.Tensor.numpy(tTensor)
toTorch = t.from_numpy(ndArray)
print(f"converted types: {toNp.dtype} (to NumPy), {toTorch.dtype} (to PyTorch)")

default types: torch.float32 (PyTorch), float64 (NumPy)

converted types: float32 (to NumPy), torch.float64 (to PyTorch)


In [80]:
x = t.ones(5)
ndArray = t.Tensor.numpy(x)
#x += ndArray[0]
#x += ndArray[0]
#x += ndArray[0]
#x[0] = 10

#Note: the 2 arrays are kind of connected when I use +=, I have no clue what's happening
x, ndArray

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [81]:
x = x + 1
ndArray[0] = 10

x, ndArray

(tensor([2., 2., 2., 2., 2.]), array([10.,  1.,  1.,  1.,  1.], dtype=float32))

When converting a tensor/ndArray, the resulting array does **not** share the same memory as the old one, so they are independent of one another.